[application]
name = "notes-supply-site"
default_platform = "web"
out_dir = "dist"
public_dir = "public"
tailwind_input = "style/input.css"
tailwind_output = "public/assets/style.css"

[web.app]
title = "notes.supply"

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = ["src", "public", "style", "index.html"]

[[web.proxy]]
backend = "http://127.0.0.1:4000/api/"

[web.resource]
style = ["/assets/style.css"]
script = ["/app/ui.js", "/app/home.js"]

[web.resource.dev]
style = []
script = []
